name: bellucare
description: "weseeks bellucare service"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.2
  go_router: ^14.6.2
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  health: ^12.0.1
  device_info_plus: ^11.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/font/Pretendard-Thin.ttf
          weight: 100
        - asset: asset/font/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: asset/font/Pretendard-Light.ttf
          weight: 300
        - asset: asset/font/Pretendard-Regular.ttf
          weight: 400
        - asset: asset/font/Pretendard-Medium.ttf
          weight: 500
        - asset: asset/font/Pretendard-SemiBold.ttf
          weight: 600
        - asset: asset/font/Pretendard-Bold.ttf
          weight: 700
        - asset: asset/font/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: asset/font/Pretendard-Black.ttf
          weight: 900
